version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.7

    working_directory: /go/src/github.com/minami14/go-bitarray
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go test -v ./...